const PFActionTypes = {
  UNSOLD_ADD_NEW_ITEM: 'UNSOLD_ADD_NEW_ITEM',
  UNSOLD_DRAFT_SYMBOL_UPDATE: 'UNSOLD_DRAFT_SYMBOL_UPDATE',
  UNSOLD_DRAFT_QUANTITY_UPDATE: 'UNSOLD_DRAFT_QUANTITY_UPDATE',
  UNSOLD_DRAFT_BASIS_UPDATE: 'UNSOLD_DRAFT_BASIC_UPDATE',
  UNSOLD_DRAFT_DELETE: 'UNSOLD_DRAFT_DELETE',
  UNSOLD_DRAFT_SAVE: 'UNSOLD_DRAFT_SAVE',

  UNSOLD_QUANTITY_UPDATE: 'UNSOLD_QUANTITY_UPDATE',
  UNSOLD_BASIS_UPDATE: 'UNSOLD_BASIS_UPDATE',
  UNSOLD_DELETE_ROW: 'UNSOLD_DELETE_ROW',

  COOKIE_DATA_LOADED: 'COOKIE_DATA_LOADED',
  MARKET_DATA_UPDATE: 'MARKET_DATA_UPDATE',
};

export default PFActionTypes;
